### ISSUE TITLE
2nd currency spam bot store 

### ISSUE THREAD

**Issue by officialCorndog** [nikgame33/POE-ChatBotDestroyer#4]
W\I/W . perandus .{ {} |\|\ Super awesome currency store is back .Anyone remember us? Come to enjoy cheap and instant currency servers.<<Cha*s=0.012 Exa|ted=1.4>> and Tabula Rasa Simple Robe=0.5 all (USMoney)

I always see this copy pasted as is

suggest "cheap and instant currency servers"

**Comment by nikgame33** [comment]
as it contains cheap it is a match for the regex and it should run.
Please go aheadd for some further tests, for me it works with current master 429b27a
